server:
  port: 8083

logging:
  level:
    com.joe.sms: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:stmsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  hibernate:
    ddl-auto: update
